[pytest]
log_cli=True
log_cli_level=DEBUG
; --html=report.html = pip install pytest-html
addopts=--failed-first --cov=src/bucket-api --cov=src/pubsub-api --junit-xml=build/test-result.xml --html=build/test-report.html --cov-report=xml:build/test-coverage.xml 
junit_family=legacy
; --cov-branch 
; norecursedirs=.pyenv-python
env =
    D:GOOGLE_APPLICATION_CREDENTIALS=.sa
    D:GCS_BUCKET_NAME={PROJECT_ID}-bucket-api